import React, { createContext, useContext, useState, useEffect } from 'react';

export type Lang = 'en' | 'he';

const translations = {
  en: {
    // Nav
    recipeBuilder:       'Recipe Builder',
    settings:            'Settings',
    bomHistory:          'BOM History',
    baseRecipes:         'Base Recipes',
    finalProducts:       'Final Products',
    // Recipe type toggle
    recipeTypeLabel:     'Recipe Type',
    baseRecipeOption:    'Base Recipe',
    finalProductOption:  'Final Packaged Product',
    // App header
    bomSystem:           'BOM & Recipe System',
    productionMgmt:      'Production Management',
    // Recipe Builder
    recipeName:          'Recipe Name',
    recipeNamePlaceholder:'e.g. Croissant Dough',
    referenceCode:       'Reference Code',
    yieldKg:             'Yield (KG)',
    ingredient:          'Ingredient Name',
    qty:                 'QTY (KG)',
    costPerKg:           'Cost per KG',
    lineCost:            'Line Cost',
    totals:              'Totals',
    addIngredient:       '+ Add Ingredient',
    clear:               'Clear',
    saveRecipe:          'Save Recipe',
    saving:              'Saving…',
    searchPlaceholder:   'Search ingredient or recipe…',
    noResults:           'No results found',
    searching:           'Searching…',
    subRecipe:           'Sub-Recipe',
    raw:                 'Raw',
    // Production costs
    productionCosts:     'Production Costs',
    perBatch:            'per batch',
    labor:               'Labor',
    overhead:            'Overhead',
    totalProduction:     'Total Production',
    productionCostsBreakdown: 'Production costs per batch:',
    // Live preview bar
    livePreview:         'Live Preview',
    totalRecipeCost:     'Total Recipe Cost',
    yieldLabel:          'Yield',
    // Table headers
    ofCostPct:           '% of Cost',
    wastePct:            'Waste %',
    // Header fields
    pricingStrategy:     'Pricing Strategy',
    autoCalculate:       'Auto-Calculate (Recommended)',
    // Misc
    unsavedChanges:      'Unsaved changes',
    // Formula Manager
    pricingFormulas:     'Pricing Formula Manager',
    addUpdateFormula:    'Add / Update Formula',
    scope:               'Scope',
    scopeId:             'Scope ID',
    category:            'Category',
    wholesaleMult:       'Wholesale Multiplier',
    retailMult:          'Retail Multiplier',
    wholesaleMargin:     'Wholesale margin',
    retailMargin:        'Retail margin',
    saveFormula:         'Save Formula',
    selectCategory:      '— select category —',
    formulaDefault:      'Default',
    formulaSetDefault:   'Set as default',
    formulaDefaultBadge: 'DEFAULT',
    formulaCannotDeleteDefault: 'Cannot delete the default formula. Mark another formula as default first.',
    // BOM History
    bomHistoryTitle:     'BOM History',
    bomHistoryDesc:      'Cost-change logs and BOM revision history will appear here.',
    refCode:             'Ref Code',
    linesHeader:         'Lines',
    ver:                 'Ver.',
    lastUpdated:         'Last Updated',
    actions:             'Actions',
    edit:                'Edit',
    delete:              'Delete',
    noSavedRecipes:      'No saved recipes yet. Build and save your first recipe.',
    loading:             'Loading…',
    failedToLoad:        'Failed to load BOM history.',
    // Import / Export toolbar
    rioSearchPlaceholder:    'Search by name or code…',
    rioFromDate:             'From',
    rioToDate:               'To',
    rioClearFilters:         'Clear filters',
    rioSelectedCount:        '{n} selected',
    rioImportBtn:            'Import',
    rioExportBtn:            'Export',
    rioTemplateBtn:          'Download template',
    rioExportSelected:       'Export selected',
    rioExportFiltered:       'Export filtered',
    rioExportFailed:         'Export failed',
    rioTemplateFailed:       'Could not download the template.',
    rioNoRowsToExport:       'No recipes match the current filters.',
    rioRecipesShown:         '{n} of {total} recipes',
    // Import modal
    rioImportTitle:          'Import recipes from Excel',
    rioImportSubtitle:       'Upload a .xlsx prepared from the template. One row per ingredient; recipe-level fields on the first row of each recipe.',
    rioDropFileHere:         'Drop your .xlsx file here',
    rioOrBrowse:             'or click to browse',
    rioFileSelected:         'File selected',
    rioFileRemove:           'Remove',
    rioOnDuplicateLabel:     'If a recipe with the same name or code already exists',
    rioOnDuplicateUpdate:    'Update it (new version)',
    rioOnDuplicateSkip:      'Skip it',
    rioDefaultTypeLabel:     'Default Recipe Type when not specified in the file',
    rioStartImport:          'Start import',
    rioImporting:            'Importing…',
    rioCancel:               'Cancel',
    rioClose:                'Close',
    rioDownloadTemplateLink: 'Download the template',
    // Import report
    rioReportTitle:          'Import results',
    rioReportTotal:          'Total',
    rioReportCreated:        'Created',
    rioReportUpdated:        'Updated',
    rioReportSkipped:        'Skipped',
    rioReportFailed:         'Failed',
    rioReportRow:            'Row',
    rioReportName:           'Recipe',
    rioReportStatus:         'Status',
    rioReportMessage:        'Details',
    rioReportEmpty:          'No recipes were processed.',
    rioImportFailedTitle:    'Import failed',
    // Where Used (Traceability)
    whereUsed:                 'Where Used',
    whereUsedTitle:            'Where Used — Traceability',
    whereUsedDesc:             'Find all recipes that use a specific ingredient or sub-assembly anywhere in their BOM tree.',
    whereUsedSearchPlaceholder:'Search by name or reference code…',
    whereUsedNoSelection:      'Search for an ingredient or sub-assembly above to see which recipes use it.',
    whereUsedNotUsed:          'This item is not used in any active recipe.',
    whereUsedRecipeCol:        'Recipe',
    whereUsedDepthCol:         'Depth',
    whereUsedDirect:           'direct',
    whereUsedLevels:           'levels',
    whereUsedNotFound:         'Item not found.',
    whereUsedUsedInPre:        'is used in',
    whereUsedUsedInPost:       'recipe',
    whereUsedUsedInPlural:     'recipes',
    // Validation errors
    validationErrorTitle:  'Please fix the following errors before saving',
    missingRecipeName:     'Recipe Name is required.',
    missingReferenceCode:  'Reference Code is required.',
    invalidYield:          'Yield must be a number greater than 0.',
    emptyIngredients:      'Add at least one ingredient.',
    invalidIngredientRow:  'Each ingredient row must have a selected item and a quantity greater than 0.',
    // Final products list pricing columns
    totalCost:           'Total Cost',
    tkpPrice:            'TKP Price',
    sellingPrice:        'Selling Price',
    // Generic
    noFormulas:          'No formulas configured yet — add one below.',
    // Login page
    loginTitle:          'Sign In',
    loginSubtitle:       'BOM & Recipe Management System',
    loginUsername:       'Username',
    loginUsernamePh:     'Enter your username',
    loginCode:           'System Code',
    loginCodePh:         'Enter your system code',
    loginButton:         'Sign In',
    loginLoading:        'Signing in…',
    loginError:          'Invalid username or code. Please try again.',
    logout:              'Sign Out',
    // Recipe Book (customer-facing)
    recipeBook:              'Recipe Book',
    recipeBookSubtitle:      'Browse recipes, scale to any batch size, and print prep sheets.',
    rbSearchPlaceholder:     'Search recipes by name or reference…',
    rbFilterAll:             'All',
    rbFilterCategory:        'Category',
    rbFilterAllergen:         'Allergen',
    rbFilterSpicy:           'Spicy only',
    rbSpicyTag:              'Spicy',
    rbAllergenLabel:         'Contains',
    rbNoRecipes:             'No recipes match your filters.',
    rbServings:              'Servings',
    rbServingSuggestion:     'Serving suggestion',
    rbTotalWeight:           'Net weight',
    rbViewRecipe:            'Open',
    rbBackToList:            '← Back to Recipe Book',
    rbIngredientsHeader:     'Ingredients',
    rbQuantityHeader:        'Quantity',
    rbWasteHeader:           'Waste',
    rbCostPerKgHeader:       'Cost / kg',
    rbLineCostHeader:        'Line cost',
    rbBatchCostsLabel:       'Per-batch additions',
    // Calculator
    calcTitle:               'Scale this recipe',
    calcDesiredWeight:       'How much to produce (kg)',
    calcRun:                 'Calculate',
    calcRunning:             'Calculating…',
    calcEnoughForServings:   'Enough for ~{n} servings',
    calcResultTitle:         'Scaled batch',
    calcScaleFactor:         'Scale factor',
    calcMaterialCost:        'Materials',
    calcLabor:               'Labor',
    calcOverhead:            'Overhead',
    calcPackaging:           'Packaging',
    calcTotalCost:           'Total cost',
    calcWholesaleTotal:      'Wholesale total',
    calcRetailTotal:         'Retail total',
    calcShoppingList:        'Aggregated shopping list',
    calcShoppingListNote:    'Total raw-material quantities across all sub-recipes.',
    calcSubRecipeOf:         'Sub-recipe',
    calcNoPriceData:         'Price information is hidden for your account.',
    calcPrintPrepSheet:      'Print prep sheet',
    calcPrintingTitle:       'Prep Sheet',
    calcEnterAmount:         'Enter a target weight to see scaled quantities.',
    calcFormulaApplied:      'Formula applied',
    calcManualOverride:      'manual override',
    calcAutoSelection:       'auto-selected',
    // Admin: Dashboard / Logs / Users / Sync
    dashboard:               'Dashboard',
    dashboardWelcome:        'Overview',
    dashSummaryBase:         'Base recipes',
    dashSummaryFinal:        'Final products',
    dashSummaryProducts:     'Raw materials',
    dashSummaryAdmins:       'Admins',
    dashSummaryCustomers:    'Customers',
    dashSummaryInactive:     'Inactive users',
    dashLastSync:            'Last Odoo sync',
    dashSyncOk:              'Last sync succeeded',
    dashSyncFailed:          'Last sync failed',
    dashSyncNever:           'No sync recorded yet',
    dashQuickActions:        'Quick actions',
    users:                   'Users',
    usersTitle:              'User Management',
    usersDesc:               'Create users and set their passwords, promote / demote, override price visibility, or deactivate access. Each user can change their own password from the menu in the top bar.',
    userColRole:             'Role',
    userColUser:             'User',
    userColCanViewPrices:    'Can view prices',
    userColActive:           'Active',
    userColLastLogin:        'Last login',
    userColActions:          'Actions',
    userCvpDefault:          'Default (role-based)',
    userCvpYes:              'Yes',
    userCvpNo:               'No',
    userActivate:            'Activate',
    userDeactivate:          'Deactivate',
    userSavePending:         'Saving…',
    // Create user + password management
    userCreateTitle:         'Create user',
    userAddNew:              '+ New user',
    userFieldUsername:       'Username',
    userFieldName:           'Full name',
    userFieldEmail:          'Email',
    userFieldPassword:       'Password',
    userFieldRole:           'Role',
    userRoleAdmin:           'Admin',
    userRoleCustomer:        'Customer',
    userCreateBtn:           'Create user',
    userCreating:            'Creating…',
    userCreatedToast:        'User created',
    userCreateFailed:        'Could not create user',
    userResetPwBtn:          'Reset password',
    userResetPwPrompt:       'Enter a new password for {name}:',
    userResetPwToast:        'Password reset',
    userResetPwFailed:       'Could not reset password',
    // Change own password (header)
    changePwMenu:            'Change password',
    changePwTitle:           'Change password',
    changePwCurrent:         'Current password',
    changePwNew:             'New password',
    changePwConfirm:         'Confirm new password',
    changePwSubmit:          'Update password',
    changePwSaving:          'Updating…',
    changePwSuccess:         'Password updated',
    changePwMismatch:        'New passwords do not match.',
    changePwTooShort:        'Password must be at least 4 characters.',
    changePwCancel:          'Cancel',
    logs:                    'Logs',
    logsTitle:               'Audit Log',
    logsDesc:                'Login events, user changes, pricing-formula edits, sync runs and customer calculations.',
    logsExportCsv:           'Export CSV',
    logsActionType:          'Action type',
    logsUser:                'User',
    logsFrom:                'From',
    logsTo:                  'To',
    logsApplyFilter:         'Apply',
    logsClearFilter:         'Clear',
    logsColTime:             'Timestamp',
    logsColUser:             'User',
    logsColAction:           'Action',
    logsColEntity:           'Entity',
    logsColDescription:      'Description',
    logsColIp:               'IP',
    logsNoRows:              'No log entries match the current filters.',
    logsShowingCount:        'Showing {n} of {total}',
    odooSync:                'Odoo Sync',
    odooSyncDesc:            'The cron job runs every {schedule}.  Trigger a manual sync below if you just updated products in Odoo.',
    odooSyncManual:          'Run sync now',
    odooSyncRunning:         'Syncing… this can take 30s+',
    odooSyncDoneToast:       'Odoo sync complete',
    odooSyncFailToast:       'Odoo sync failed',
    odooSyncRecalc:          'Recalculate all recipe costs',
    odooSyncRecalcDoneToast: 'Cost recalculation complete',
    odooSyncCronSchedule:    'Cron schedule',
    odooSyncActiveProducts:  'Active raw materials',
    odooSyncLastTrigger:     'Last triggered',
    odooSyncLastOutcome:     'Last outcome',
    rbStalePinWarning:       'Selected formula no longer exists — fell back to the default formula.',
    rbFormulaSection:        'Pricing formula',
    rbFormulaAuto:           'Use default formula',
    rbFormulaActiveLabel:    'Currently applied',
    // Recipe Book extra fields shown in builder
    rbFieldFullName:         'Display name (full title)',
    rbFieldDescription:      'Description',
    rbFieldAllergens:        'Allergens (comma-separated)',
    rbFieldIsSpicy:          'Spicy',
    rbFieldServingSuggestion:'Serving suggestion',
    rbFieldServingsCount:    'Servings per yield',
    rbFieldTotalWeight:      'Total net weight (kg)',
    rbBrandingSection:       'Recipe-book card',
    rbFieldImageHint:        'Click to upload image',
    rbViewPrint:             'Print',
    rbViewPdf:               'PDF',
    rbViewPrintTitle:        'Print or save as PDF',
    settingsTabFormulas:     'Pricing formulas',
    settingsTabUsers:        'Users',
    settingsTabSync:         'ERP integration',
    // ERP integration tab (demo messaging)
    erpTitle:                'ERP Integration (API)',
    erpDemoBadge:            'Demo mode',
    erpDemoNote:             'This is a demo system, so the catalogue is filled with sample data. In the production system the app connects via API to the factory’s existing ERP system, and products and costs are synced from it automatically.',
    erpRecalcNote:           'You can recalculate all recipe costs from the current data:',
    formulaNameLabel:        'Formula name',
    formulaPriorityLabel:    'Priority',
    // Products tab (admin-only Odoo catalogue)
    products:                'Products',
    productsTitle:           'Products — Catalogue',
    productsSearchPlaceholder: 'Search by name or reference…',
    productsSortHint:        'Click to sort',
    productsColImage:        'Image',
    productsColName:         'Product name',
    productsColWeight:       'Weight',
    productsColCost:         'Cost',
    productsColCostPerKg:    'Cost / kg',
    productsWeightMissing:   'Weight missing — cannot compute',
    productsCpkStored:       'Showing stored cost_per_kg from items table',
    productsCpkComputed:     'Computed live: raw_cost / weight (g) × 1000',
    productsCpkStoredTag:    'stored',
    productsCpkComputedTag:  'computed',
    productsEmpty:           'No raw-material products synced yet.',
    productsNoMatches:       'No products match the current search.',
    productsEstimatedFromName: 'Estimated from name',
    productsEstimatedTag:    'estimated',
    productsWeightFromRegex: 'Weight parsed from product name (no Odoo weight)',
    productsCpkFromRegex:    'Cost-per-kg uses name-extracted weight (estimated)',
  },
  he: {
    // Nav
    recipeBuilder:       'בניית מתכון',
    settings:            'הגדרות',
    bomHistory:          'היסטוריית BOM',
    baseRecipes:         'מתכוני בסיס',
    finalProducts:       'מוצרים סופיים',
    // Recipe type toggle
    recipeTypeLabel:     'סוג מתכון',
    baseRecipeOption:    'מתכון בסיס',
    finalProductOption:  'מוצר ארוז סופי',
    // App header
    bomSystem:           'מערכת BOM ומתכונים',
    productionMgmt:      'ניהול ייצור',
    // Recipe Builder
    recipeName:          'שם המתכון',
    recipeNamePlaceholder:'לדוגמה: בצק קרואסון',
    referenceCode:       'קוד אסמכתה',
    yieldKg:             'תפוקה (ק"ג)',
    ingredient:          'שם המרכיב',
    qty:                 'כמות (ק"ג)',
    costPerKg:           'עלות לק"ג',
    lineCost:            'עלות שורה',
    totals:              'סכומים',
    addIngredient:       '+ הוסף מרכיב',
    clear:               'נקה',
    saveRecipe:          'שמור מתכון',
    saving:              'שומר…',
    searchPlaceholder:   'חפש מרכיב או מתכון...',
    noResults:           'לא נמצאו תוצאות',
    searching:           'מחפש…',
    subRecipe:           'תת-מתכון',
    raw:                 'חומר גלם',
    // Production costs
    productionCosts:     'עלויות ייצור',
    perBatch:            'לאצווה',
    labor:               'עבודה',
    overhead:            'הוצאות עקיפות',
    totalProduction:     'סה"כ ייצור',
    productionCostsBreakdown: 'עלויות ייצור לאצווה:',
    // Live preview bar
    livePreview:         'תצוגה חיה',
    totalRecipeCost:     'עלות מתכון כוללת',
    yieldLabel:          'תפוקה',
    // Table headers
    ofCostPct:           '% מהעלות',
    wastePct:            'פחת %',
    // Header fields
    pricingStrategy:     'אסטרטגיית תמחור',
    autoCalculate:       'חישוב אוטומטי (מומלץ)',
    // Misc
    unsavedChanges:      'שינויים שלא נשמרו',
    // Formula Manager
    pricingFormulas:     'מנהל נוסחאות תמחור',
    addUpdateFormula:    'הוסף / עדכן נוסחה',
    scope:               'היקף',
    scopeId:             'מזהה היקף',
    category:            'קטגוריה',
    wholesaleMult:       'מכפיל סיטונאי',
    retailMult:          'מכפיל קמעוני',
    wholesaleMargin:     'שולי סיטונאי',
    retailMargin:        'שולי קמעוני',
    saveFormula:         'שמור נוסחה',
    selectCategory:      '— בחר קטגוריה —',
    formulaDefault:      'ברירת מחדל',
    formulaSetDefault:   'הגדר כברירת מחדל',
    formulaDefaultBadge: 'ברירת מחדל',
    formulaCannotDeleteDefault: 'לא ניתן למחוק את נוסחת ברירת המחדל. סמן נוסחה אחרת כברירת מחדל תחילה.',
    // BOM History
    bomHistoryTitle:     'היסטוריית BOM',
    bomHistoryDesc:      'יומני שינויי עלויות והיסטוריית גרסאות BOM יופיעו כאן.',
    refCode:             'קוד אסמכתה',
    linesHeader:         'שורות',
    ver:                 'גרסה',
    lastUpdated:         'עדכון אחרון',
    actions:             'פעולות',
    edit:                'ערוך',
    delete:              'מחק',
    noSavedRecipes:      'אין מתכונים שמורים עדיין. בנה ושמור את המתכון הראשון שלך.',
    loading:             'טוען…',
    failedToLoad:        'טעינת היסטוריית BOM נכשלה.',
    // Import / Export toolbar
    rioSearchPlaceholder:    'חיפוש לפי שם או קוד…',
    rioFromDate:             'מתאריך',
    rioToDate:               'עד תאריך',
    rioClearFilters:         'נקה סינון',
    rioSelectedCount:        '{n} מסומנים',
    rioImportBtn:            'ייבוא',
    rioExportBtn:            'ייצוא',
    rioTemplateBtn:          'הורד קובץ דוגמה',
    rioExportSelected:       'ייצוא המסומנים',
    rioExportFiltered:       'ייצוא המסונן',
    rioExportFailed:         'הייצוא נכשל',
    rioTemplateFailed:       'לא ניתן היה להוריד את הקובץ.',
    rioNoRowsToExport:       'אין מתכונים שתואמים לסינון.',
    rioRecipesShown:         '{n} מתוך {total} מתכונים',
    // Import modal
    rioImportTitle:          'ייבוא מתכונים מאקסל',
    rioImportSubtitle:       'העלה קובץ .xlsx שהוכן לפי הדוגמה. שורה אחת לכל רכיב; שדות המתכון בשורה הראשונה של כל מתכון.',
    rioDropFileHere:         'גרור את קובץ ה-xlsx לכאן',
    rioOrBrowse:             'או לחץ לבחירת קובץ',
    rioFileSelected:         'הקובץ נבחר',
    rioFileRemove:           'הסר',
    rioOnDuplicateLabel:     'אם מתכון עם אותו שם או קוד כבר קיים',
    rioOnDuplicateUpdate:    'עדכן אותו (גרסה חדשה)',
    rioOnDuplicateSkip:      'דלג עליו',
    rioDefaultTypeLabel:     'סוג מתכון ברירת מחדל כשלא צוין בקובץ',
    rioStartImport:          'התחל ייבוא',
    rioImporting:            'מייבא…',
    rioCancel:               'ביטול',
    rioClose:                'סגירה',
    rioDownloadTemplateLink: 'הורד קובץ דוגמה',
    // Import report
    rioReportTitle:          'תוצאות הייבוא',
    rioReportTotal:          'סה"כ',
    rioReportCreated:        'נוצרו',
    rioReportUpdated:        'עודכנו',
    rioReportSkipped:        'דולגו',
    rioReportFailed:         'נכשלו',
    rioReportRow:            'שורה',
    rioReportName:           'מתכון',
    rioReportStatus:         'סטטוס',
    rioReportMessage:        'פרטים',
    rioReportEmpty:          'לא עובדו מתכונים.',
    rioImportFailedTitle:    'הייבוא נכשל',
    // Where Used (Traceability)
    whereUsed:                 'שימוש ברכיבים',
    whereUsedTitle:            'שימוש ברכיבים — מעקב',
    whereUsedDesc:             'מצא את כל המתכונים שמשתמשים ברכיב מסוים או תת-הרכבה בכל עץ ה-BOM שלהם.',
    whereUsedSearchPlaceholder:'חפש לפי שם או קוד אסמכתה…',
    whereUsedNoSelection:      'חפש מרכיב או תת-הרכבה כדי לראות אילו מתכונים משתמשים בו.',
    whereUsedNotUsed:          'פריט זה לא נמצא בשימוש באף מתכון פעיל.',
    whereUsedRecipeCol:        'מתכון',
    whereUsedDepthCol:         'עומק',
    whereUsedDirect:           'ישיר',
    whereUsedLevels:           'רמות',
    whereUsedNotFound:         'פריט לא נמצא.',
    whereUsedUsedInPre:        'משמש ב-',
    whereUsedUsedInPost:       'מתכון',
    whereUsedUsedInPlural:     'מתכונים',
    // Validation errors
    validationErrorTitle:  'נא תקן את השגיאות הבאות לפני השמירה',
    missingRecipeName:     'שם המתכון נדרש.',
    missingReferenceCode:  'קוד אסמכתה נדרש.',
    invalidYield:          'התפוקה חייבת להיות מספר גדול מ-0.',
    emptyIngredients:      'הוסף לפחות מרכיב אחד.',
    invalidIngredientRow:  'לכל שורת מרכיב חייב להיות פריט נבחר וכמות גדולה מ-0.',
    // Final products list pricing columns
    totalCost:           'מחיר עלות',
    tkpPrice:            'מחיר TKP',
    sellingPrice:        'מחיר מכירה',
    // Generic
    noFormulas:          'אין נוסחאות מוגדרות עדיין — הוסף אחת למטה.',
    // Login page
    loginTitle:          'כניסה למערכת',
    loginSubtitle:       'מערכת BOM וניהול מתכונים',
    loginUsername:       'שם משתמש',
    loginUsernamePh:     'הכנס שם משתמש',
    loginCode:           'קוד כניסה',
    loginCodePh:         'הכנס את קוד המערכת',
    loginButton:         'כניסה',
    loginLoading:        'מתחבר…',
    loginError:          'שם משתמש או קוד שגוי. אנא נסה שוב.',
    logout:              'יציאה',
    // Recipe Book (customer-facing)
    recipeBook:              'ספר המתכונים',
    recipeBookSubtitle:      'דפדף במתכונים, שנה גודל אצווה והדפס דפי הכנה.',
    rbSearchPlaceholder:     'חפש מתכון לפי שם או קוד אסמכתה…',
    rbFilterAll:             'הכל',
    rbFilterCategory:        'קטגוריה',
    rbFilterAllergen:        'אלרגן',
    rbFilterSpicy:           'חריף בלבד',
    rbSpicyTag:              'חריף',
    rbAllergenLabel:         'מכיל',
    rbNoRecipes:             'לא נמצאו מתכונים תואמים לסינון.',
    rbServings:              'מנות',
    rbServingSuggestion:     'הצעת הגשה',
    rbTotalWeight:           'משקל נטו',
    rbViewRecipe:            'פתח',
    rbBackToList:            '→ חזרה לספר המתכונים',
    rbIngredientsHeader:     'מרכיבים',
    rbQuantityHeader:        'כמות',
    rbWasteHeader:           'פחת',
    rbCostPerKgHeader:       'עלות / ק"ג',
    rbLineCostHeader:        'עלות שורה',
    rbBatchCostsLabel:       'תוספות לאצווה',
    // Calculator
    calcTitle:               'התאם גודל אצווה',
    calcDesiredWeight:       'כמה לייצר (ק״ג)',
    calcRun:                 'חשב',
    calcRunning:             'מחשב…',
    calcEnoughForServings:   'מספיק ל-~{n} מנות',
    calcResultTitle:         'אצווה מותאמת',
    calcScaleFactor:         'מקדם התאמה',
    calcMaterialCost:        'חומרי גלם',
    calcLabor:               'עבודה',
    calcOverhead:            'הוצאות',
    calcPackaging:           'אריזה',
    calcTotalCost:           'עלות כוללת',
    calcWholesaleTotal:      'סיטונאי כולל',
    calcRetailTotal:         'קמעוני כולל',
    calcShoppingList:        'רשימת קניות מצטברת',
    calcShoppingListNote:    'סך כמויות חומרי גלם בכל תתי-המתכונים.',
    calcSubRecipeOf:         'תת-מתכון',
    calcNoPriceData:         'מידע מחיר מוסתר עבור החשבון שלך.',
    calcPrintPrepSheet:      'הדפס דף הכנה',
    calcPrintingTitle:       'דף הכנה',
    calcEnterAmount:         'הזן משקל יעד כדי לראות כמויות מותאמות.',
    calcFormulaApplied:      'נוסחה הוחלה',
    calcManualOverride:      'עקיפה ידנית',
    calcAutoSelection:       'נבחר אוטומטית',
    // Admin: Dashboard / Logs / Users / Sync
    dashboard:               'לוח בקרה',
    dashboardWelcome:        'סקירה',
    dashSummaryBase:         'מתכוני בסיס',
    dashSummaryFinal:        'מוצרים סופיים',
    dashSummaryProducts:     'חומרי גלם',
    dashSummaryAdmins:       'מנהלים',
    dashSummaryCustomers:    'לקוחות',
    dashSummaryInactive:     'משתמשים לא פעילים',
    dashLastSync:            'סנכרון אחרון מאודו',
    dashSyncOk:              'סנכרון אחרון הצליח',
    dashSyncFailed:          'סנכרון אחרון נכשל',
    dashSyncNever:           'אין סנכרון רשום',
    dashQuickActions:        'פעולות מהירות',
    users:                   'משתמשים',
    usersTitle:              'ניהול משתמשים',
    usersDesc:               'צור משתמשים והגדר להם סיסמאות, קדם/הורד תפקיד, עקוף נראות מחירים או השבת גישה. כל משתמש יכול לשנות את הסיסמה שלו מהתפריט בסרגל העליון.',
    userColRole:             'תפקיד',
    userColUser:             'משתמש',
    userColCanViewPrices:    'רואה מחירים',
    userColActive:           'פעיל',
    userColLastLogin:        'כניסה אחרונה',
    userColActions:          'פעולות',
    userCvpDefault:          'ברירת מחדל (לפי תפקיד)',
    userCvpYes:              'כן',
    userCvpNo:               'לא',
    userActivate:            'הפעל',
    userDeactivate:          'השבת',
    userSavePending:         'שומר…',
    // Create user + password management
    userCreateTitle:         'יצירת משתמש',
    userAddNew:              '+ משתמש חדש',
    userFieldUsername:       'שם משתמש',
    userFieldName:           'שם מלא',
    userFieldEmail:          'אימייל',
    userFieldPassword:       'סיסמה',
    userFieldRole:           'תפקיד',
    userRoleAdmin:           'מנהל',
    userRoleCustomer:        'לקוח',
    userCreateBtn:           'צור משתמש',
    userCreating:            'יוצר…',
    userCreatedToast:        'המשתמש נוצר',
    userCreateFailed:        'יצירת המשתמש נכשלה',
    userResetPwBtn:          'איפוס סיסמה',
    userResetPwPrompt:       'הזן סיסמה חדשה עבור {name}:',
    userResetPwToast:        'הסיסמה אופסה',
    userResetPwFailed:       'איפוס הסיסמה נכשל',
    // Change own password (header)
    changePwMenu:            'שינוי סיסמה',
    changePwTitle:           'שינוי סיסמה',
    changePwCurrent:         'סיסמה נוכחית',
    changePwNew:             'סיסמה חדשה',
    changePwConfirm:         'אישור סיסמה חדשה',
    changePwSubmit:          'עדכן סיסמה',
    changePwSaving:          'מעדכן…',
    changePwSuccess:         'הסיסמה עודכנה',
    changePwMismatch:        'הסיסמאות החדשות אינן תואמות.',
    changePwTooShort:        'הסיסמה חייבת להכיל לפחות 4 תווים.',
    changePwCancel:          'ביטול',
    logs:                    'יומנים',
    logsTitle:               'יומן ביקורת',
    logsDesc:                'אירועי כניסה, שינויי משתמשים, עריכת נוסחאות תמחור, ריצות סנכרון וחישובי לקוח.',
    logsExportCsv:           'יצא ל-CSV',
    logsActionType:          'סוג פעולה',
    logsUser:                'משתמש',
    logsFrom:                'מתאריך',
    logsTo:                  'עד תאריך',
    logsApplyFilter:         'החל',
    logsClearFilter:         'נקה',
    logsColTime:             'זמן',
    logsColUser:             'משתמש',
    logsColAction:           'פעולה',
    logsColEntity:           'ישות',
    logsColDescription:      'תיאור',
    logsColIp:               'IP',
    logsNoRows:              'אין רשומות יומן התואמות לסינון.',
    logsShowingCount:        'מציג {n} מתוך {total}',
    odooSync:                'סנכרון אודו',
    odooSyncDesc:            'משימת ה-cron רצה כל {schedule}.  הפעל סנכרון ידני אם עדכנת מוצרים באודו.',
    odooSyncManual:          'הרץ סנכרון עכשיו',
    odooSyncRunning:         'מסנכרן… יכול לקחת 30 שניות',
    odooSyncDoneToast:       'סנכרון אודו הסתיים',
    odooSyncFailToast:       'סנכרון אודו נכשל',
    odooSyncRecalc:          'חשב מחדש את כל עלויות המתכונים',
    odooSyncRecalcDoneToast: 'חישוב מחדש של עלויות הסתיים',
    odooSyncCronSchedule:    'לוח זמני cron',
    odooSyncActiveProducts:  'חומרי גלם פעילים',
    odooSyncLastTrigger:     'הופעל לאחרונה',
    odooSyncLastOutcome:     'תוצאה אחרונה',
    rbStalePinWarning:       'הנוסחה הנבחרת לא קיימת — חזר לנוסחת ברירת המחדל.',
    rbFormulaSection:        'נוסחת תמחור',
    rbFormulaAuto:           'השתמש בנוסחת ברירת המחדל',
    rbFormulaActiveLabel:    'פעיל כעת',
    // Recipe Book extra fields shown in builder
    rbFieldFullName:         'שם תצוגה (כותרת מלאה)',
    rbFieldDescription:      'תיאור',
    rbFieldAllergens:        'אלרגנים (מופרדים בפסיק)',
    rbFieldIsSpicy:          'חריף',
    rbFieldServingSuggestion:'הצעת הגשה',
    rbFieldServingsCount:    'מנות לתפוקה',
    rbFieldTotalWeight:      'משקל נטו כולל (ק״ג)',
    rbBrandingSection:       'כרטיס ספר מתכונים',
    rbFieldImageHint:        'לחצי להעלאת תמונה',
    rbViewPrint:             'הדפסה',
    rbViewPdf:               'PDF',
    rbViewPrintTitle:        'הדפסה או שמירה כ-PDF',
    settingsTabFormulas:     'נוסחאות תמחור',
    settingsTabUsers:        'משתמשים',
    settingsTabSync:         'התממשקות ERP',
    // ERP integration tab (demo messaging)
    erpTitle:                'התממשקות API עם מערכת ERP',
    erpDemoBadge:            'מצב דמו',
    erpDemoNote:             'זוהי מערכת דמו, ולכן הקטלוג מכיל נתוני דמו. במערכת האמיתית האפליקציה מתחברת ב-API למערכת ה-ERP הקיימת של המפעל, והמוצרים והעלויות מסתנכרנים ממנה אוטומטית.',
    erpRecalcNote:           'אפשר לחשב מחדש את כל עלויות המתכונים מהנתונים הנוכחיים:',
    formulaNameLabel:        'שם הנוסחה',
    formulaPriorityLabel:    'עדיפות',
    // Products tab (admin-only Odoo catalogue)
    products:                'מוצרים',
    productsTitle:           'מוצרים — קטלוג',
    productsSearchPlaceholder: 'חפש לפי שם או קוד אסמכתה…',
    productsSortHint:        'לחץ למיון',
    productsColImage:        'תמונה',
    productsColName:         'שם המוצר',
    productsColWeight:       'משקל',
    productsColCost:         'עלות',
    productsColCostPerKg:    'עלות / ק״ג',
    productsWeightMissing:   'משקל חסר — לא ניתן לחשב',
    productsCpkStored:       'מציג cost_per_kg שמור מטבלת items',
    productsCpkComputed:     'חישוב חי: raw_cost / משקל (גרם) × 1000',
    productsCpkStoredTag:    'שמור',
    productsCpkComputedTag:  'חי',
    productsEmpty:           'אין חומרי גלם מסונכרנים עדיין.',
    productsNoMatches:       'אין מוצרים תואמים לחיפוש.',
    productsEstimatedFromName: 'מוערך משם המוצר',
    productsEstimatedTag:    'מוערך',
    productsWeightFromRegex: 'המשקל חולץ משם המוצר (לא מאודו)',
    productsCpkFromRegex:    'עלות/ק״ג מבוססת על משקל שחולץ מהשם (הערכה)',
  },
} as const;

// Translations type covers both langs.  We widen each value to `string`
// so EN-vs-HE literal differences don't cause an assignability error
// at the <Provider> boundary, while keeping the EN key-set as the
// authoritative shape (any missing key surfaces as a property error).
export type Translations = { readonly [K in keyof typeof translations['en']]: string };

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextValue>({
  lang: 'en',
  setLang: () => {},
  t: translations.en,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('bom_lang') as Lang) ?? 'en';
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('bom_lang', l);
  };

  useEffect(() => {
    document.documentElement.setAttribute('dir',  lang === 'he' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang === 'he' ? 'he'  : 'en');
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
